### ISSUE TITLE
Give the option to manually set location in the settings

### ISSUE THREAD

**Issue by mybox1** [JasonPuglisi/descent#110]
Hi!
I am using this great website on wallpaper engine, and I can use the settings menu within the game/app. But there is currently no way to let Wallpaper Engine accept having it's location set, as you can in Chrome for example. So there is no way to see what the weather or temperature is like from the website on Wallpaper Engine.

Being able to manually type in my location in the settings would be a great way around this, and you would be able to have the correct location if you were using a VPN for example.

I am sorry if this was a poorly written issue, I am not a coder. But I figured I would give it a go asking for it.

Have a great day, and thanks for the awesome website, I am really loving it:)

**Comment by JasonPuglisi** [comment]
Done, hope it's still useful! :)
