### ISSUE TITLE
Currently broken?

### ISSUE THREAD

**Issue by hans-juergen** [JasonPuglisi/descent#115]
Hi Jason, I am trying to use Descent currently scrobbling with my account from Spotify, "Scrobbling now" is shown in my Recent tracks, but Descent keeps telling me "Nothing in the air..." My username is hjbardenhagen, and I have tried enabling all options, so at least the extended info should show. I'm using a dark mode script on Last.fm which does not seem to affect Descent anyhow, and I also have disabled the uBlock origin ad-blocker.

**Comment by JasonPuglisi** [comment]
Weird, I'm traveling right now so I can't troubleshoot much, but it appears to be working for me. Sometimes there are temporary API or rate limit issues, so let me know if it gets better for you. If not, I can look into it more in a few days. Thanks!

**Comment by hans-juergen** [comment]
Thank you for replying. In the meantime I found out that I cannot see my scrobbles, but e.g. those of UK and U.S. users without problems. So maybe it has to do with my location in Germany. I will try to use Descent in Opera, as it has a free VPN service.

By the way, a Last.fm staff member just checked my username in Descent, and he got the same result of "Nothing in the air..."

**Comment by hans-juergen** [comment]
OK, you can close the issue, I had forgotten that I had disabled showing my recent tracks in my profile, d'oh!
