### ISSUE TITLE
Nothing is displaying, it was yesterday

### ISSUE THREAD

**Issue by caleb-gamer** [JasonPuglisi/descent#136]
![image](https://user-images.githubusercontent.com/89547443/211817909-f8b919f0-bcc5-4d4d-89a7-0aeac2cffcdf.jpg)

**Comment by caleb-gamer** [comment]
I have spent the last 30 mins troubleshooting this

**Comment by hans-juergen** [comment]
What's your Last.fm username? It works for me without problems at the moment. Maybe you have disabled showing your recent tracks on your user profile in your [Last.fm privacy settings](https://www.last.fm/settings/privacy)?

**Comment by caleb-gamer** [comment]
calebgamer

**Comment by JasonPuglisi** [comment]
I can confirm it looks like a problem with your privacy settings. Your recent play history is not available. Thanks @hans-juergen for the suggestion, that should fix things!

**Comment by caleb-gamer** [comment]
Alr thank you

**Comment by JasonPuglisi** [comment]
It looks like it's working for you now! Do you need help with something else? There's no Discord for this project at least.

**Comment by caleb-gamer** [comment]
Well the weather is acting weird, right now it seems correct but it was wrong earlier when I tried to set the coordinates it said -7F°. It’s 50F°

**Comment by caleb-gamer** [comment]
Virginia Beach, Virginia it’s 50 and it says 6

**Comment by caleb-gamer** [comment]
36.8516N 75.9792W

**Comment by JasonPuglisi** [comment]
Make sure you do -75.9792 for longitude since W is negative 😄 I tested and that looks like the difference between 6 and 50

**Comment by caleb-gamer** [comment]
Ok thank you
