### ISSUE TITLE
Takes 37 seconds to update

### ISSUE THREAD

**Issue by caleb-gamer** [JasonPuglisi/descent#137]
It takes 37 seconds to update when I change the song on Spotify

**Comment by JasonPuglisi** [comment]
Last.fm sometimes has some delay with Spotify. If you see the currently playing track updated on your profile, it should update on Descent within a few seconds. But if Last.fm is slow to update your profile, there's not much Descent can do :(

If you want to test, can you watch how long it takes between Last.fm updating your currently playing, and Descent doing so?

**Comment by JasonPuglisi** [comment]
Closing this for now, but feel free to comment if you want to troubleshoot more
