### ISSUE TITLE
Add option to display a user's last scrobble instead of what is "now scrobbling"

### ISSUE THREAD

**Issue by mdrxy** [JasonPuglisi/descent#149]
Certain Scrobblers don't have the option to push a "now scrobbling" message to Last.fm. Displaying the most recently scrobbled song can alleviate this problem in Descent.

**Comment by JasonPuglisi** [comment]
It's a fair request, but I don't really have the time/resources to do feature work on Descent anymore, and not sure when that will change. I'll leave the issue open in case someone wants to submit a PR for it.
