### ISSUE TITLE
Webapp LastFM won’t work with the username

### ISSUE THREAD

**Issue by mawewo** [JasonPuglisi/descent#156]
Such a lovely web application! Everything works well beside the main thing… the last fm integration… when adding the username, nothing happens. Just says „nothing in the air“… but in last fm I see the scrobbling works well. Also when being logged out of last fm in browser I can access my Profil. So it’s accessible for everyone. Also tried several browsers. Safari, chromium, Firefox… none of them worked..

**Comment by JasonPuglisi** [comment]
When you're playing music, on your Last.fm profile, does it show "Scrobbling now"? Or does the track only appear after you've finished listening? If you provide your Last.fm username, I can take a look too.

**Comment by mawewo** [comment]
Thanks for the very fast respond!
Currently my profile is available for everyone. The listening history also. If you mean this? Checked in my profile settings.
My last fm username is: mawewo
Thanks for your help so far!

**Comment by JasonPuglisi** [comment]
Gotcha, what music service are you scrobbling from? And are you using any software/extensions that aren't built-in to the music service? Certain services/software don't update the "now playing" status on Last.fm profiles, which causes Descent not to work.

**Comment by mawewo** [comment]
You are damn right! It’s this „now playing“ feature from lastfm. Tested a few services. Tidal transmits a current playing song as ‚now playing‘ to lastfm. Qobuz, which I am using sadly does not. Damn. So I can’t use your Webapp… :( love it so much… best, Matteo

**Comment by hans-juergen** [comment]
It's the same with the internal scrobbling option of Deezer. If you use external scrobbling apps with Qobuz like the Web Scrobbler browser extension for their web player or an Android app like Pano Scrobbler on your Android phone, they will send the "Scrobbling now" info to your Last.fm profile, and Descent can use it.
