### ISSUE TITLE
Spotify: No API Credentials

### ISSUE THREAD

**Issue by pete2583** [JasonPuglisi/descent#162]
Hey, I imagine it's something I'm doing wrong but I can't get it to connect to Spotify. 

Where exactly am I supposed to put my client id and secret? Perhaps I've put it in the wrong place, it's not overly clear in the ReadMe.

Cheers

**Comment by JasonPuglisi** [comment]
They should go in the `SPOTIFY_CLIENT` and `SPOTIFY_SECRET` environment variables

**Comment by pete2583** [comment]
Yeah, I thought that. 

As in replace every time they are mentioned? 

Sorry, I know I'm being dumb but I'm fairly certain I put them in the right place but every time it runs out days no api

**Comment by pete2583** [comment]
Or just lines 18/19 on server js?

**Comment by JasonPuglisi** [comment]
You don’t need to modify the code at all! Environment variables are set in your terminal and the program picks them up automatically. For example, here’s some instructions to set environment variables on Linux: https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-linux

Might be different depending what operating system you’re using.

**Comment by pete2583** [comment]
Oh jeez, that makes total sense. I knew I was being dumb but just couldn't get my head around it the other day. Granted I think a few beers had been consumed lol
