### ISSUE TITLE
Dark Reader tool for using dark mode on all browser tabs disables Descent background images

### ISSUE THREAD

**Issue by hans-juergen** [JasonPuglisi/descent#164]
Just FYI, as I noticed this while having [Dark Reader](https://microsoftedge.microsoft.com/addons/detail/dark-reader/ifoakfbpdcdoeenechcleahebpibofpc) enabled with Descent: there are no background images anymore, no matter how you configure them, just a black background. You can configure Dark Reader to disable it for certain URLs, so I guess you can avoid it that way. Maybe Descent can also do something about it?

**Comment by JasonPuglisi** [comment]
I think the best solution is to disable the extension for Descent. Extensions like this break normal browser behavior and it's hard to engineer around them, especially as the behavior could change at any moment.

**Comment by hans-juergen** [comment]
Thanks for replying, the configuration setting of Dark Reader has a tab with a list for websites that it should or should not work on. I added "descent.live/hjbardenhagen" to the latter which enables the background images of Descent again.
