### ISSUE TITLE
Artist image not showing on some artists?

### ISSUE THREAD

**Issue by KatyLB** [JasonPuglisi/descent#60]
Hi, not sure why this might be but the artist image doesn't appear in the background for some artists, e.g. The Primitives and Taleen Kali, despite them having artist images uploaded. Is there a reason for this or is this a bug?

**Comment by JasonPuglisi** [comment]
I'm getting an image for The Primitives but not Taleen Kali. It seems Last.fm isn't supplying an artist ID with the track info that's used to get the artist image. In any case, it's probably possible to do a search for the artist name if Last.fm doesn't give us the ID directly.

Might get around to fixing this but I haven't been very active with development of this project lately...

**Comment by KatyLB** [comment]
Thanks for the reply. I'm going to raise the issue with the Last.fm staff (I'm a moderator so I communicate directly with them) to see if it's a known bug on that end.

I'm finding sometimes the artist image isn't loading. I don't get an artist image for X or for The Enemy, for example, along with The Primitives that I mentioned before. I don't know if this is because some requests also aren't providing the ID you need, and some are.

**Comment by KatyLB** [comment]
I tested The Primitives again, by the way. I still don't get an artist image, even though you are. Not sure why it would work for me and not for you?

Artist: The Primitives
Track: Thru the Flowers
Album: Lovely
Album Artist: The Primitives

**Comment by JasonPuglisi** [comment]
It looks like it's the same issue for the other artists you mentioned. For example, here's an API response for a Soft Science song:

```json
{
  "track": [
      {
        "artist": {
          "mbid": "",
          "#text": "Soft Science"
        },
        "@attr": {
          "nowplaying": "true"
        },
        "mbid": "19554e4d-179b-4eaf-bc8f-1c2f6df000cc",
        "album": {
          "mbid": "63f22c27-5759-4e0a-b62f-6c31d15ed965",
          "#text": "Maps"
        },
        "streamable": "0",
        "url": "https:\/\/www.last.fm\/music\/Soft+Science\/_\/Undone",
        "name": "Undone",
        "image": [
          {
            "size": "small",
            "#text": "https:\/\/lastfm-img2.akamaized.net\/i\/u\/34s\/bd5e202a3b67ff723e7d99d3483aae5d.jpg"
          },
          {
            "size": "medium",
            "#text": "https:\/\/lastfm-img2.akamaized.net\/i\/u\/64s\/bd5e202a3b67ff723e7d99d3483aae5d.jpg"
          },
          {
            "size": "large",
            "#text": "https:\/\/lastfm-img2.akamaized.net\/i\/u\/174s\/bd5e202a3b67ff723e7d99d3483aae5d.jpg"
          },
          {
            "size": "extralarge",
            "#text": "https:\/\/lastfm-img2.akamaized.net\/i\/u\/300x300\/bd5e202a3b67ff723e7d99d3483aae5d.jpg"
          }
        ]
      }
    ]
  }
}
```

Specifically, notice how `mbid` under `artist` is blank. Still, Thru the Flowers and other tracks are not giving me a problem:

![image](https://user-images.githubusercontent.com/5090549/57077151-4d1ce680-6cb9-11e9-83f1-73656bbcbcc6.png)

**Comment by KatyLB** [comment]
Ah, it seems like some of the examples may be due to the artists being too obscure for MusicBrainz (e.g. Taleen Kali), although Soft Science are in MusicBrainz (https://musicbrainz.org/artist/0f83f567-99cd-4815-89c9-2a68ce8c4e59) and The Primitives issue still affects me for some reason.

Incidentally, Last.fm have just announced some API changes which might prevent you from getting images from Last.fm (which was against the Terms of Use for the API) in future, I can't be sure if it'll affect you or require a switch to other services for that data. Here's the link: https://getsatisfaction.com/lastfm/topics/api-announcement-dac8oefw5vrxq

**Comment by JasonPuglisi** [comment]
I think the best solution will be searching for the artist name if we don't get a MBID back. That should solve issues with more obscure artists and possibly the issue with The Primitives as well.

I've noted the API change. It shouldn't really affect the application as we should be able to still get that data from Spotify.

**Comment by KatyLB** [comment]
That's cool and sounds like a good solution, hopefully you'll be able to find the time to make that tweak!

**Comment by KatyLB** [comment]
I'm getting a no image type thumbnail for the artist for The Strokes, which I assume is related to the API changes?

**Comment by JasonPuglisi** [comment]
That seems to be the case. I'm pushing a change now that will use Spotify for all artist images, and might solve some missing image issues. Sadly, with the Last.fm API now limiting images, any remaining missing/incorrect images cannot be fixed by this application. For reference, I've detailed limitations in PR #61.
