### ISSUE TITLE
Last.fm no longer returning album art

### ISSUE THREAD

**Issue by JasonPuglisi** [JasonPuglisi/descent#62]
Need to migrate to Spotify Web API

**Comment by KatyLB** [comment]
If you require a fallback option from Spotify, you could consider services such as Google Play, iTunes, Tidal or Deezer, but not sure how useful they would be as I know they can sometimes have less artist images or (in the case of Deezer, for example) quite outdated and generally poor ones. Another solution, although I guess it'd be harder, would be to build your own database of artist images to use as an override or when they're unavailable elsewhere, which would protect against any changes to the Spotify API and allow for issues with artists not being found that way to be solved.

**Comment by JasonPuglisi** [comment]
We'll see how it goes for now! I'd like to avoid adding another API integration, especially if the API in question is paid or has restrictive usage limits (I haven't yet checked if this is the case for any of the ones you mentioned.) Sadly, to build such a database myself would require lots of time and money just to host/serve the images.

**Comment by KatyLB** [comment]
Cool! Well, the good news is that using Spotify now is resulting in images showing for obscure newer artists, the bad thing being all of the not-so-great images for older artists (like Björk, for one) that it's giving, but I guess that can't be avoided without having some sort of override.
