### ISSUE TITLE
Customization options and Spotify playing data

### ISSUE THREAD

**Issue by hans-juergen** [JasonPuglisi/descent#67]
Thanks for the new version, looks very good on my Sony Bravia TV set (40" screen with 1280x768 resolution) as second monitor using it in full screen mode with 125% zoom in MS Edge. I like the switch to Spotify, as it uses different images than Last.fm which are interesting to watch in my opinion. Hopefully you can use their API for free in the future as well.

Two little changes would be nice to have: an option for the date to day/month/year sorting and a variable setting for the background shading if possible. For example I might prefer even 0% of shading on the new screen now or maybe only 20% with no blur.

I am noticing that releases of classical music might be incorrect due to the album that gets actually played by Spotify instead of what Last.fm assumes might be correct and/or the "main" album for that track. So would it be possible to get the Now Playing info directly from the Spotify API now that you take the pictures from there anyhow?

**Comment by KatyLB** [comment]
> So would it be possible to get the Now Playing info directly from the Spotify API now that you take the pictures from there anyhow?

Wouldn't this be turning it into a Spotify Now Playing site? I mean, such a Descent alternative would be an interesting thing for Jason to develop (it might get a lot of use from Spotify users), but I'd hate to see it done as an override to Last.fm data. I personally would like Descent to show what I'm listening to according to Last.fm, not another service.

**Comment by JasonPuglisi** [comment]
I was actually thinking about getting Now Playing info from Spotify yesterday. It would certainly solve metadata/image matching issues for those using Spotify (I only scrobble from there myself). However, I believe there are a fair amount of users who probably don't use Spotify, so maybe I'll add it as an alternative option to Last.fm in the future.

With the recent API change, I thought Last.fm was getting rid of album covers too (and just not artists), so I'm now using Spotify for both. If album cover matching with Spotify seems to be working poorly, I might switch back to getting them from Last.fm.

**Comment by hans-juergen** [comment]
Having "Now Playing" from Spotify as an option would probably be the best of both worlds. Also keep in mind that Spotify only offers a rather bad full screen mode to Premium users, free accounts cannot use it. So those users would probably like this option in your app.

An example for a typical mismatch in classical music would be this track from my new Release Radar playlist: https://open.spotify.com/track/3qOg4MsU7zB4FSyInCbEwd

It is the fourth movement of Symphony No. 5 by Sergei Prokofiev from the album "Milestones of a Legend: Sergei Prokofiev, Vol. 4" with George Szell conducting the Cleveland Orchestra. Last.fm picked another performance of that piece with Leonard Bernstein and the New Philharmonia Orchestra on another album for "Scrobbling now" showing that album cover instead.

**Comment by KatyLB** [comment]
If you want to do everything from Spotify that's fine, but that'll be the end of my interest in your site. I don't use Spotify so it'd be a pointless tool for me. I suspect you'd lose a lot of your users as well.

Personally I'd just make a Spotify version and a Last.fm version and let people decide, then make one of them descent.live/spotify and one descent.live/last.fm, or something like that.

**Comment by JasonPuglisi** [comment]
I think we all agree having Spotify as a second option would be nice! I don’t think anyone suggested getting rid of Last.fm entirely. The API changes hurt a bit, but I have no desire to disobey terms of service, so I’d rather not get any album or artist images from Last.fm. We can only hope the rules are relaxed a bit in the future.

This started off as a personal project because it was something I wanted. It doesn’t have ads or make money in any way. In fact, it just costs more to run the more users it has. Still, I develop/host it with the spirit of hoping as many people can find it useful as possible.

**Comment by hans-juergen** [comment]
I added a related thread with screenshots on the new support forum, as the old Get Satisfaction forum does not exist anymore:
https://support.last.fm/t/full-screen-mode-for-last-fm/16306

**Comment by JasonPuglisi** [comment]
Awesome, thanks for the mention and heads up!

**Comment by JasonPuglisi** [comment]
This issue has been open for a while, and unfortunately I think it would add scope and maintenance to the project that I'm not interested in taking on. In order to clean up some older issues, I'm going to close this with the `wontfix` label, but anyone is still welcome to fork the project and implement it if desired!
