### ISSUE TITLE
Default picture while playing songs without album/artist image

### ISSUE THREAD

**Issue by owaimori** [JasonPuglisi/descent#71]
sorry for my bad english
now while playing song which doesnt have artist and album images i just see previous artist image or gray screen
maybe could be better if currently playing song doesnt have picture which need be used for backgroud (album or artist, which user choose in settings) instead of gray screen (or previos artist image) there will be default picture like when user dont listen any music?

also i try to use this site for my desktop wallpapers trough wallpaper engine (just set url to page)
![image](https://user-images.githubusercontent.com/31232219/58095446-af437a00-7bdb-11e9-9f78-f176dfe877eb.png)

it looks cool but when currently playing song doesnt have images it looks empty >w>  
![image](https://user-images.githubusercontent.com/31232219/58095115-e9f8e280-7bda-11e9-8156-1a7e3444e5e3.png)
sadly song name on right bottom not visible behind the windows menu (i know i can hide windows menu but i like to see it)

**Comment by JasonPuglisi** [comment]
How about if you change "Default image URL" in the settings? https://descent.live/now/app/config

I can't test it right now but if that doesn't work, it shouldn't be too hard to fix.

**Comment by owaimori** [comment]
i already change it when make this screens, but if i open page (or reload) when playing song which havent artist cover i see gray screen, and if i not reload page i see backgroud drom last song which have artist image

**Comment by hans-juergen** [comment]
> I can't test it right now but if that doesn't work, it shouldn't be too hard to fix.

Maybe you should simply show the last scrobbled track in this case, also if there is no "Now playing" info from the streaming site like Deezer. The Last.fm Now Playing feature for subscribers does it that way which makes more sense than showing an empty screen:

https://www.last.fm/user/hjbardenhagen/now

**Comment by JasonPuglisi** [comment]
I’ll this and fix it not showing the default background the next time I do some development. It is intentional to have the check mark as a save button, but maybe I’ll change it to be more clear.

I didn’t even know they added back a now playing feature! I wonder how long that’s been around.

**Comment by hans-juergen** [comment]
They reintroduced it some time after the release of the new website in 2015, but only for subscribers. You can click on the "Scrobbling now" link in your Recent Tracks list, then it will open the Now Playing page.

**Comment by JasonPuglisi** [comment]
A number of issues identified here:
- Scrobbling a new song without identifiable artwork will not clear the background image (it does appear to clear the album art).
- Text is too low when used as a desktop wallpaper. Might consider moving the text up but it would affect all users.
- It's not clear that the save button (checkmark) needs to be clicked. Might change the icon, add text, and/or make it autosave.

I don't think I'm going to try showing the most recent song played if none are active, but I'll at least fix the buggy background.

**Comment by JasonPuglisi** [comment]
I fixed these issues except for the text being too low. Unfortunately, I don't plan to change the text positioning.
