### ISSUE TITLE
A question - how to align to center

### ISSUE THREAD

**Issue by jbrepogmailcom** [JasonPuglisi/descent#77]
Hello, I have rather a question than issue.

Thanks for really great and neat product. I use it for long time.

On widescreen monitor, there is too much free space on right side, I would prefer to have image and title centered. Could you please advise me how to modify css file?

Thank you very much, Jan

**Comment by JasonPuglisi** [comment]
There's currently no way to do this, but I may add an option in the future if I continue development at some point. If you want to do this yourself, you can change a few of the alignment options in `source/scss/now.scss` and recompile according to the `README`, but I can't provide specific guidance. Closing this issue as I'm tracking future work in #76.
