### ISSUE TITLE
A question: Cover art for www.streamingsoundtracks.com

### ISSUE THREAD

**Issue by jbrepogmailcom** [JasonPuglisi/descent#79]
Hello!

Do you think you may like to create similar page to display art of streaming soundtrack at streamingsoundtracks.som? In the source code of main page, the ID code (asin) of current album is contained in link like "http://www.streamingsoundtracks.com/modules.php?name=Album&asin=B01EMCBULY" and then the image can be linked by the album ID as "http://www.streamingsoundtracks.com/images/cover/500/B01EMCBULY.jpg". The code changes every few minutes as soundtracks change.

I can display the cover art, but it is not that neat like your descent.

Thanks, Jan

**Comment by JasonPuglisi** [comment]
Unfortunately I don't plan on supporting any other sources besides Last.fm, and possibly Spotify. It might not be too hard to fork this project and use streamingsoundtracks.com instead of Last.fm if you or someone else would like to develop it.
