### ISSUE TITLE
Not displaying what I'm listening to, when Last.fm is says I have something scrobbling now

### ISSUE THREAD

**Issue by AndrewRobinson1** [JasonPuglisi/descent#90]
Hi there, when I go on Descent and enter my lastfm username (AndrewRobinson1), it shows "Nothing in the air...", even when there is something showing as scrobbling now on my lastfm page. Hopefully it's just something I'm messing up somehow, but the site used to work for me.

**Comment by JasonPuglisi** [comment]
Is your profile/history set to private? It looks like the API request for your recent tracks is failing with error `Login: User required to be logged in`, so that's my first guess.

**Comment by AndrewRobinson1** [comment]
It was, must've changed that one day without realizing

**Comment by JasonPuglisi** [comment]
Glad that fixed it!
