### ISSUE TITLE
Album Art

### ISSUE THREAD

**Issue by yinka** [JasonPuglisi/descent#94]
Thanks for this gem, I use it everyday

Is there a way to increase the album art please?

**Comment by hans-juergen** [comment]
You can zoom the browser page, the background image stays the same.

**Comment by yinka** [comment]
True, thanks

**Comment by JasonPuglisi** [comment]
Yeah, I would suggest the zoom strategy, as I'm not planning to add options for album size currently. I'll note that the design is kind of behind the times these days, so maybe I'll start thinking about doing an overhaul in the near/mid future. More prominent album art and text and whatnot :)
