### ISSUE TITLE
I think it's dead. 

### ISSUE THREAD

**Issue by LemonCat** [JasonPuglisi/descent#97]

**Comment by JasonPuglisi** [comment]
Hey @LemonCat what issue are you having? Seems to be working fine for me

**Comment by LemonCat** [comment]
I never have anything displayed for my account LemonQwaz, even though I'm scrobbling, and it's displayed as such on lastfm website. 

Sorry for not answering in time. 

![image](https://user-images.githubusercontent.com/4086748/120985817-43a9b680-c77c-11eb-9bc3-d9bfc918d23b.png)
![image](https://user-images.githubusercontent.com/4086748/120985840-49070100-c77c-11eb-9a37-b87230b2817f.png)
![image](https://user-images.githubusercontent.com/4086748/120985859-4d331e80-c77c-11eb-9ce2-f36c819d23e4.png)

**Comment by hans-juergen** [comment]
In your screenshot there is no thumbnail shown for the currently scrobbling track, that means there is no album artwork available which could be used for Descent. This is the Last.fm album page:
https://www.last.fm/music/Matt+Fax/Obsidian
